### Example on how to get the top N element

`np.argsort()` sort from small to large, return their indexes

Index from big to small is `[3,4,0,5,1,2]`

In [94]:
a = np.array([4, 1, 0, 8, 5, 2])
asort = np.argsort(a)[::-1][:5]; print(asort) # [3,4,0,5,1,2]
asort[::1][:3]

[3 4 0 5 1]


array([3, 4, 0], dtype=int64)

### Exanple on reversing and subseting array

`a[::-1]` reverse the order to big to small

`a[:5]` take the first 5 elements

In [93]:
a = np.array([0, 1, 2, 3, 4, 5]) 
print(a[::-1]) # reverse the order of elements in a
print(a[:5])
print(a[::-1][:3])

[5 4 3 2 1 0]
[0 1 2 3 4]
[5 4 3]
